-- =====================================================================
--  CRM Groupe — lot 8 : les fiches DTU qui restaient vides
--  À exécuter dans Supabase > SQL Editor, après lot7-btp-dtu.sql.
--  Idempotent : relançable, il réécrit le même contenu.
--
--  13 fiches n'avaient que leur numéro et leur intitulé. Elles reçoivent ici
--  leur résumé, leurs points clés et leurs erreurs fréquentes, dans la même forme
--  que celles venues du tableau de bord RGD Renova.
--
--  ATTENTION — ce contenu a été rédigé à partir de connaissances générales du
--  bâtiment, pas recopié des normes elles-mêmes. Les valeurs chiffrées y sont
--  données en ordre de grandeur et renvoient au texte officiel. À relire par le
--  cabinet avant de s'en servir en expertise : c'est votre signature qui l'engage.
--
--  Les points de contrôle du cabinet (colonne checkpoints) ne sont pas touchés.
-- =====================================================================

update public.dtu_sheets set
  summary = 'Semelles filantes et isolées sur sol porteur. La fondation conditionne tout le reste : une erreur ici se lit en fissures sur toute la hauteur du bâtiment, des années plus tard.',
  key_points = '[{"titre":"Étude de sol préalable","detail":"La nature du sol commande tout : profondeur d''assise, largeur de semelle, ferraillage. Sur sol argileux (retrait-gonflement), l''étude géotechnique est obligatoire pour les maisons individuelles depuis la loi ELAN. Sans étude, on dimensionne à l''aveugle et l''assureur peut se retourner."},{"titre":"Mise hors gel de l''assise","detail":"Profondeur minimale variable selon la région et l''altitude : de l''ordre de 50 cm en plaine littorale, 80 cm à 1 m en zone continentale, davantage en montagne. Une semelle prise dans la zone de gel se soulève l''hiver et redescend au dégel : fissuration cyclique caractéristique."},{"titre":"Assise sur sol homogène","detail":"Toute la semelle doit reposer sur le même horizon géologique. En terrain en pente ou hétérogène, on redente par paliers, jamais en biais. Une semelle à cheval sur deux natures de sol tasse de façon différentielle : la fissure part en escalier depuis le point de rupture."},{"titre":"Béton de propreté","detail":"Couche de 4 à 5 cm coulée en fond de fouille avant le ferraillage. Elle isole les aciers de la terre, garantit l''enrobage en sous-face et donne un fond plan pour caler les armatures. Ferrailler directement sur la terre expose les aciers à la corrosion."},{"titre":"Continuité du ferraillage","detail":"Les aciers longitudinaux sont continus sur tout le linéaire, avec recouvrements soignés et retours d''angle. Une semelle interrompue aux angles ne travaille plus comme un cadre : chaque tronçon tasse pour son compte."},{"titre":"Drainage périphérique","detail":"En terrain humide ou en pente, drain en pied de fondation sur lit de gravier, avec pente d''écoulement et exutoire identifié. L''eau stagnante au contact de la fondation ramollit le sol d''assise et met le mur en charge."}]'::jsonb,
  common_errors = '[{"titre":"Absence d''étude de sol en zone argileuse","detail":"C''est le grand classique du sinistre sécheresse : fissures traversantes en escalier sur les façades, portes et fenêtres qui coincent, l''été après une saison sèche. Réparation par reprise en sous-œuvre, très coûteuse."},{"titre":"Fondation trop peu profonde","detail":"Semelle dans la zone de gel ou dans la couche de terre végétale. Le bâtiment bouge au rythme des saisons, les fissures s''ouvrent et se referment — signature typique d''un défaut d''assise."},{"titre":"Semelle à cheval sur remblai et terrain naturel","detail":"Le remblai se compacte encore pendant des années, pas le terrain naturel. Tassement différentiel garanti, avec fissure verticale nette à l''aplomb de la limite."},{"titre":"Pas de redent en terrain en pente","detail":"Une semelle inclinée glisse. Les redents doivent être horizontaux, avec une hauteur de marche limitée et un recouvrement d''armatures à chaque décrochement."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-13-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 13.1');

update public.dtu_sheets set
  summary = 'Cuvelage des parties enterrées : sous-sols, caves, parkings. On traite ici l''eau sous pression, pas la simple humidité — la différence change tout dans le choix de la solution.',
  key_points = '[{"titre":"Identifier la sollicitation réelle","detail":"Eau de ruissellement, humidité du sol ou nappe phréatique permanente : les trois ne se traitent pas de la même façon. Un cuvelage se dimensionne sur le niveau des plus hautes eaux connues, pas sur le niveau constaté le jour de la visite."},{"titre":"Trois familles de cuvelage","detail":"Revêtement d''imperméabilisation appliqué à l''intérieur, structure relativement étanche par le béton lui-même, ou revêtement d''étanchéité rapporté. Le choix dépend de la pression d''eau et de l''usage du local. Le mortier hydrofuge seul ne tient pas contre une nappe."},{"titre":"Traitement des points singuliers","detail":"Angles, reprises de bétonnage, traversées de canalisations et jonction avec le dallage concentrent les entrées d''eau. Chaque point singulier a son traitement propre : gorge d''angle, joint waterstop, manchette. C''est là que ça fuit, jamais en pleine surface."},{"titre":"Résistance du support","detail":"Le revêtement intérieur doit être appliqué sur un béton sain et cohésif, décapé de toute laitance. Sur support friable ou fissuré, le revêtement est chassé par la pression d''eau, quelle que soit sa qualité."},{"titre":"Anticiper la sous-pression","detail":"Un sous-sol étanche dans une nappe subit une poussée d''Archimède. Le dallage doit être lesté ou ancré, sinon il se soulève et se fissure au centre. C''est un calcul, pas une appréciation."}]'::jsonb,
  common_errors = '[{"titre":"Confondre drainage et cuvelage","detail":"Un drain périphérique gère des venues d''eau limitées ; il ne remplace pas un cuvelage sous nappe. Le drain se colmate en quelques années et la cave se remet en eau."},{"titre":"Enduit hydrofuge appliqué côté intérieur seul","detail":"Sous pression, l''eau décolle le revêtement par l''arrière. Cloques, puis plaques qui tombent, et le problème revient identique après travaux."},{"titre":"Points singuliers oubliés","detail":"Traversée de canalisation non traitée : une seule suffit pour inonder le local malgré un cuvelage par ailleurs correct."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-14-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 14.1');

update public.dtu_sheets set
  summary = 'L''exécution des ouvrages en béton : coffrage, ferraillage, coulage, cure. Le DTU de référence dès qu''il y a du béton structurel sur le chantier.',
  key_points = '[{"titre":"Enrobage des armatures","detail":"C''est la distance entre l''acier et la surface du béton, et c''est ce qui protège l''acier de la corrosion. De l''ordre de 3 cm en intérieur sec, 4 cm et plus en extérieur ou milieu agressif. Garanti par des cales, jamais à l''œil. Enrobage insuffisant : l''acier rouille, gonfle, et fait éclater le béton."},{"titre":"Cales d''armatures obligatoires","detail":"Cales béton ou plastique, réparties, pour tenir les aciers en position pendant le coulage. Des armatures posées au fond ou remontées à la main pendant la vibration ne sont plus là où le calcul les avait placées."},{"titre":"Vibration du béton","detail":"Aiguille vibrante par passes verticales, retirée lentement, sans traîner l''aiguille horizontalement pour faire couler le béton. Une vibration insuffisante laisse des nids de cailloux ; une vibration excessive fait remonter la laitance et ségréger."},{"titre":"Reprises de bétonnage","detail":"Toute interruption de coulage crée un plan de faiblesse. La reprise se prépare : surface repiquée, nettoyée, humidifiée, et si possible armatures en attente. Une reprise non traitée est une fissure en puissance et un chemin d''eau."},{"titre":"Cure du béton","detail":"Maintien de l''humidité pendant les premiers jours : bâchage, arrosage ou produit de cure. Un béton qui sèche trop vite fissure en surface (faïençage) et n''atteint pas sa résistance. Par temps chaud ou venteux, la cure n''est pas optionnelle."},{"titre":"Conditions de bétonnage","detail":"Pas de coulage par gel sans protection, ni par forte chaleur sans adaptation. Le béton jeune gelé est définitivement compromis en surface. En période froide, on protège et on suit les températures."}]'::jsonb,
  common_errors = '[{"titre":"Aciers apparents ou trop proches du parement","detail":"Traces de rouille puis éclatement du béton par gonflement de l''acier. Très visible en sous-face de balcon et sur les nez de dalle exposés — un grand classique de l''expertise."},{"titre":"Ajout d''eau sur le chantier","detail":"Rajouter de l''eau dans la toupie pour faciliter la mise en œuvre détruit la résistance et augmente le retrait. Le béton devient poreux et fissure. Si le béton est trop ferme, c''est un adjuvant qu''il faut, pas de l''eau."},{"titre":"Reprise de bétonnage non traitée","detail":"Joint froid visible, souvent suintant. Sur un mur enterré ou une piscine, c''est par là que l''eau passe."},{"titre":"Décoffrage trop précoce","detail":"Le béton n''a pas la résistance nécessaire pour porter son propre poids : flèche résiduelle, fissuration, parfois affaissement. Les délais dépendent de la température, pas du planning."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-21'),
  updated_at = now()
where lower(code) = lower('NF DTU 21');

update public.dtu_sheets set
  summary = 'Murs en béton banché coulés en place. Courant en sous-sol, en mur de soutènement et en construction neuve — les désordres viennent presque toujours du coffrage et des reprises.',
  key_points = '[{"titre":"Stabilité et étanchéité du coffrage","detail":"Banches contreventées, serrage des tiges contrôlé, about de banche fermé. Un coffrage qui fuit laisse partir la laitance : le parement sort sableux et les aciers se retrouvent sous-enrobés au droit de la fuite."},{"titre":"Hauteur de chute du béton","detail":"Déverser de trop haut sépare les gros éléments du mortier. On utilise une goulotte ou une manchette pour limiter la chute, et on coule par couches successives vibrées."},{"titre":"Coulage par couches","detail":"Couches d''épaisseur limitée, vibrées avant que la précédente ait commencé à faire prise. Attendre trop longtemps entre deux couches crée une reprise interne invisible qui fera un plan de rupture."},{"titre":"Armatures de liaison et de chaînage","detail":"Aciers verticaux en attente pour la liaison avec le niveau suivant, chaînages en tête, renforts autour des réservations. Les angles et les jonctions de voiles se ferraillent spécifiquement."},{"titre":"Réservations prévues, pas percées après","detail":"Les passages de gaines et de canalisations sont positionnés au coffrage. Percer après coup coupe des armatures et fragilise le voile, surtout dans le tiers inférieur."}]'::jsonb,
  common_errors = '[{"titre":"Nids de cailloux en pied de voile","detail":"Zone la plus difficile à vibrer, souvent la plus mal traitée. Le béton y est poreux : infiltration en sous-sol et aciers non protégés. Réparation par ragréage structurel, jamais par simple enduit."},{"titre":"Trous de banches non obturés","detail":"Chaque tige de serrage laisse un passage traversant. Non rebouchés avec un produit adapté, ce sont autant de points d''entrée d''eau sur un mur enterré."},{"titre":"Balèvres et désaffleurs","detail":"Défauts de calage entre banches : le parement présente des décrochements. Esthétique en étage courant, mais sur un mur destiné à recevoir une étanchéité, c''est un point de percement du revêtement."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-23-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 23.1');

update public.dtu_sheets set
  summary = 'Conduits de fumée et raccordements des appareils à combustion. Le DTU le plus sensible du lot : les erreurs se paient en incendie de cheminée ou en intoxication au monoxyde.',
  key_points = '[{"titre":"Compatibilité conduit / appareil","detail":"Chaque appareil impose un type de conduit selon sa température de fumée et son mode de fonctionnement (tirage naturel, pression, condensation). La désignation du conduit (température, pression, résistance au feu de cheminée, corrosion) doit couvrir celle de l''appareil. Le raccordement d''un poêle moderne sur un conduit ancien non chemisé est le cas le plus fréquent de non-conformité."},{"titre":"Distance de sécurité aux matériaux combustibles","detail":"Un écart au feu doit être maintenu entre la paroi extérieure du conduit et tout matériau combustible, charpente et isolant compris. Cette distance est donnée par le marquage du conduit. Combler cet espace avec de la laine minérale ne le supprime pas."},{"titre":"Débouché en toiture","detail":"Le conduit doit dépasser suffisamment le faîtage et les obstacles proches pour que le tirage ne soit pas contrarié par les turbulences de vent. Un débouché trop bas donne des refoulements par vent portant — symptôme classique d''une cheminée qui enfume la pièce."},{"titre":"Étanchéité et continuité du conduit","detail":"Emboîtements dans le sens du tirage, joints adaptés à la température, pas de réduction de section ni de dévoiement excessif. Chaque coude ajoute de la perte de charge et un point d''encrassement."},{"titre":"Tubage d''un conduit existant","detail":"En rénovation, le tubage est la règle dès qu''on raccorde un appareil moderne sur un conduit maçonné ancien. Ramonage préalable, test d''étanchéité, plaque signalétique en pied de conduit indiquant les caractéristiques."},{"titre":"Amenée d''air de combustion","detail":"Un appareil consomme l''air de la pièce s''il n''est pas étanche. Dans un logement rendu très étanche par la rénovation, sans amenée d''air dédiée, l''appareil tire mal et peut refouler. La VMC aggrave le phénomène en dépressurisant le volume."}]'::jsonb,
  common_errors = '[{"titre":"Poêle raccordé sur conduit non tubé","detail":"Conduit maçonné ancien, fissuré et perméable : les fumées migrent dans la maçonnerie et vers les pièces voisines. Risque d''intoxication, et assurance qui refuse la prise en charge en cas de sinistre."},{"titre":"Isolant ou bois au contact du conduit","detail":"Dans les combles, l''isolant soufflé recouvre le conduit ou la charpente le frôle. C''est la cause directe d''incendies de toiture, parfois plusieurs années après la pose."},{"titre":"Absence de plaque signalétique","detail":"Après tubage ou création de conduit, la plaque est obligatoire. Son absence empêche de vérifier la compatibilité de tout appareil raccordé ensuite, et c''est un point de non-conformité relevé en expertise."},{"titre":"Dévoiements multiples","detail":"Trop de coudes pour contourner la charpente : tirage insuffisant, encrassement accéléré, ramonage impossible sur toute la longueur."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-24-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 24.1');

update public.dtu_sheets set
  summary = 'Chapes et dalles à base de liants hydrauliques : le support de tous les revêtements de sol. Un désordre de chape se voit toujours au revêtement, et c''est le revêtement qu''on accuse.',
  key_points = '[{"titre":"Choisir le type de chape","detail":"Adhérente, désolidarisée ou flottante : le choix dépend du support et de ce qu''il y a dessous. Une chape sur isolant ou sur plancher chauffant est toujours flottante, avec l''épaisseur minimale qui va avec — une chape trop mince casse."},{"titre":"Épaisseur minimale","detail":"Elle dépend du type de chape et de la charge d''exploitation ; une chape flottante demande nettement plus d''épaisseur qu''une chape adhérente. Sous l''épaisseur admissible, la chape fissure sous charge ponctuelle, typiquement sous les pieds de meubles."},{"titre":"Joints de fractionnement","detail":"La chape se fractionne en panneaux, avec des joints au droit des seuils de porte, aux changements de géométrie et à intervalles réguliers en grande surface. Sur plancher chauffant, ces joints sont impératifs et doivent être remontés dans le revêtement."},{"titre":"Bande périphérique","detail":"Bande compressible sur tout le pourtour, contre les murs et les émergences, remontée jusqu''au niveau fini. Elle laisse la chape se dilater sans pousser sur les cloisons et coupe le pont phonique."},{"titre":"Délai de séchage avant revêtement","detail":"Le revêtement ne se pose que sur une chape suffisamment sèche, mesure d''humidité à l''appui. Poser un carrelage ou surtout un parquet sur une chape encore humide, c''est provoquer décollements et tuilage quelques mois plus tard."},{"titre":"Planéité et cohésion du support","detail":"Contrôle à la règle et sondage. Une chape qui sonne creux ou qui poudre en surface doit être reprise avant revêtement, pas ragréée par-dessus."}]'::jsonb,
  common_errors = '[{"titre":"Revêtement posé sur chape insuffisamment sèche","detail":"Cause majeure de sinistres sur parquet collé : gonflement, tuilage, décollement. Le délai théorique ne vaut rien sans mesure, surtout en hiver ou en local non chauffé."},{"titre":"Joints de fractionnement absents","detail":"La chape fissure là où elle veut, et la fissure se propage dans le carrelage. Typiquement en travers des seuils de porte, là où la chape est étranglée."},{"titre":"Bande périphérique oubliée ou arasée trop bas","detail":"La chape prend appui sur les cloisons : fissures en pied de mur, remontée de bruit d''impact entre étages."},{"titre":"Chape flottante trop mince","detail":"Sous l''épaisseur requise, la chape travaille en flexion sur l''isolant et casse en morceaux, souvent au centre des pièces."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-26-2'),
  updated_at = now()
where lower(code) = lower('NF DTU 26.2');

update public.dtu_sheets set
  summary = 'Maisons et bâtiments à ossature bois. La performance tient à trois choses : la gestion de l''eau, la gestion de la vapeur, et le contreventement.',
  key_points = '[{"titre":"Pare-pluie côté extérieur","detail":"Membrane posée sur l''extérieur de l''ossature, recouvrements dans le sens de l''écoulement, traitement des percements. Elle protège l''ossature pendant le chantier et durablement contre l''eau qui passe derrière le bardage."},{"titre":"Lame d''air ventilée derrière le bardage","detail":"Tasseaux verticaux créant une lame d''air continue, ouverte en bas et en haut, avec grille anti-rongeurs. C''est elle qui évacue l''humidité. Un bardage cloué directement sur le pare-pluie pourrit par l''arrière."},{"titre":"Pare-vapeur côté intérieur, continu","detail":"Membrane côté chauffé, continue, avec adhésifs et manchons à chaque traversée (prises, gaines, tuyaux). La moindre déchirure laisse passer la vapeur d''eau qui condense dans l''isolant et pourrit l''ossature. C''est le défaut le plus grave et le moins visible."},{"titre":"Contreventement","detail":"Panneaux de contreventement fixés selon un plan de clouage précis : type de pointe, entraxe en rive et en partie courante. Un clouage approximatif divise la résistance du mur au vent."},{"titre":"Bois protégé de l''humidité au montage","detail":"Classe d''emploi adaptée à la position dans l''ouvrage, taux d''humidité du bois maîtrisé à la pose, ossature jamais laissée exposée à la pluie sans protection. Un bois mis en œuvre trop humide retrait, fissure et laisse jouer les assemblages."},{"titre":"Relevé en pied de mur","detail":"La lisse basse est séparée du support maçonné par une barrière d''étanchéité, et l''ossature démarre au-dessus du niveau des projections d''eau. Un pied de mur bois au contact direct du béton humide est condamné."}]'::jsonb,
  common_errors = '[{"titre":"Pare-vapeur percé ou discontinu","detail":"Boîtiers électriques posés à travers la membrane sans manchon, adhésifs non maroufl��s. La condensation s''installe dans l''isolant : moisissures, odeur, et à terme dégradation de l''ossature. Invisible jusqu''au démontage."},{"titre":"Bardage sans lame d''air","detail":"Pas de séchage possible par l''arrière. Le bardage cloque, se déforme, et le pare-pluie reste humide en permanence."},{"titre":"Lisse basse en contact avec la dalle","detail":"Remontée capillaire directe dans l''ossature. Le pied de montant pourrit sur quelques centimètres, la structure perd son appui."},{"titre":"Clouage de contreventement non conforme","detail":"Pointes trop espacées ou trop près du bord des panneaux. Le mur perd sa raideur : déformations sous vent, fissuration des finitions intérieures."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-31-2'),
  updated_at = now()
where lower(code) = lower('NF DTU 31.2');

update public.dtu_sheets set
  summary = 'Couverture en ardoises, naturelles ou fibres-ciment. Tout se joue sur la pente, le recouvrement et la fixation — trois paramètres liés entre eux.',
  key_points = '[{"titre":"Pente minimale selon la situation","detail":"La pente admissible dépend de la zone climatique, de l''exposition au vent et de la longueur de rampant. Plus le site est exposé, plus la pente exigée est forte. Poser une ardoise sous la pente minimale, c''est accepter les remontées d''eau par capillarité et par vent."},{"titre":"Recouvrement","detail":"Le recouvrement se calcule, il ne se choisit pas : il croît quand la pente diminue et quand l''exposition augmente. C''est lui qui garantit qu''une goutte d''eau poussée par le vent ne franchit pas le rang."},{"titre":"Fixation adaptée","detail":"Crochets ou clous selon la technique, en matériau compatible avec l''ardoise et résistant à la corrosion. En zone très ventée, les fixations sont renforcées en rives et en faîtage, là où la dépression est maximale."},{"titre":"Ventilation de la sous-face","detail":"Entrée d''air en égout, sortie en faîtage, section libre maintenue. Une couverture non ventilée condense en sous-face : la charpente et l''isolant prennent l''humidité, l''ardoise se dégrade par l''arrière."},{"titre":"Points singuliers","detail":"Noues, arêtiers, faîtage, rives, solins et pénétrations : chacun a son traitement. Les noues concentrent tout le débit de deux versants, c''est le point le plus sollicité de la toiture."}]'::jsonb,
  common_errors = '[{"titre":"Pente insuffisante pour la zone","detail":"Infiltrations par vent et pluie battante, sans fuite visible par temps calme. Le diagnostic se fait par recoupement avec l''exposition, pas en montant un jour de beau temps."},{"titre":"Recouvrement réduit pour économiser des ardoises","detail":"Quelques rangs gagnés sur le métrage, et des remontées d''eau sur tout le versant. Défaut systématique et non réparable localement."},{"titre":"Fixations corrodées ou inadaptées","detail":"Métal incompatible ou qualité insuffisante : les crochets cassent, les ardoises glissent. Se manifeste par des ardoises manquantes après coup de vent, toujours aux mêmes endroits."},{"titre":"Ventilation bouchée par l''isolant","detail":"Isolation des combles poussée jusqu''à l''égout, qui obture l''entrée d''air. Condensation généralisée en sous-face, souvent confondue avec une fuite."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-40-11'),
  updated_at = now()
where lower(code) = lower('NF DTU 40.11');

update public.dtu_sheets set
  summary = 'Tuiles de terre cuite à emboîtement ou à glissement : la couverture la plus répandue. Les règles de pente et de fixation dépendent directement du site.',
  key_points = '[{"titre":"Pente selon zone, site et rampant","detail":"La pente minimale se lit dans un tableau croisant la zone climatique, la situation (protégée, normale, exposée) et la longueur du rampant. Le même modèle de tuile n''a pas la même pente admissible en Provence et en bord de mer breton."},{"titre":"Fixation des tuiles","detail":"Le pourcentage de tuiles à fixer dépend de la pente et de l''exposition au vent ; en zone très exposée, on va jusqu''à tout fixer. Les tuiles de rive, d''égout, de faîtage et celles bordant les pénétrations sont toujours fixées."},{"titre":"Écran de sous-toiture","detail":"Recommandé et souvent exigé, particulièrement en site exposé ou sous faible pente. Posé avec recouvrement et lame d''air sous les liteaux, avec un traitement soigné en égout pour rejeter l''eau dans la gouttière."},{"titre":"Liteaunage régulier","detail":"L''écartement des liteaux découle du pureau de la tuile. Un liteaunage irrégulier donne des rangs qui ne s''emboîtent plus correctement et un aspect ondulé du versant."},{"titre":"Ventilation haute et basse","detail":"Section d''entrée d''air en égout et de sortie en faîtage, maintenue libre. Le faîtage à sec ventilé est devenu la règle, le faîtage scellé au mortier se fissure et bloque la ventilation."},{"titre":"Traitement des rives et des solins","detail":"Rives fixées et closes, solins contre maçonnerie réalisés avec bande porte-solin ou engravure, jamais un simple cordon de mortier. La jonction mur-toiture est un point de fuite fréquent."}]'::jsonb,
  common_errors = '[{"titre":"Pente sous le minimum du site","detail":"Très fréquent sur extensions et vérandas maçonnées. L''eau remonte sous la tuile par capillarité et par vent : traces d''humidité sur la sous-face et les murs, sans fuite franche."},{"titre":"Tuiles non fixées en rive et en faîtage","detail":"Ce sont les zones de dépression maximale. Après un coup de vent, les tuiles partent en rive alors que le reste du versant est intact."},{"titre":"Faîtage scellé au mortier","detail":"Le mortier fissure avec les mouvements de charpente et bloque la ventilation. Infiltrations en ligne de faîte et condensation sous toiture."},{"titre":"Écran de sous-toiture posé tendu jusqu''au mur","detail":"Sans rejet dans la gouttière, l''eau recueillie par l''écran se déverse en tête de mur. Humidité localisée en haut de façade, souvent attribuée à tort à la maçonnerie."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-40-21'),
  updated_at = now()
where lower(code) = lower('NF DTU 40.21');

update public.dtu_sheets set
  summary = 'Toitures-terrasses sur éléments porteurs en bois et panneaux dérivés du bois. Le bois supporte mal l''eau : la moindre erreur d''étanchéité ou de ventilation se paie par la structure.',
  key_points = '[{"titre":"Pente minimale respectée","detail":"La terrasse doit évacuer l''eau, y compris avec la flèche de la structure sous charge. Une pente nulle ou contrariée crée des flaches permanentes qui sollicitent le revêtement en continu et accélèrent son vieillissement."},{"titre":"Pare-vapeur sous l''isolant","detail":"Indispensable sur support bois : sans lui, la vapeur du logement traverse le plancher et condense sous l''étanchéité. L''eau reste piégée entre deux membranes et le bois pourrit sans qu''aucune fuite n''apparaisse à l''intérieur."},{"titre":"Relevés d''étanchéité","detail":"Hauteur de relevé suffisante au-dessus de la protection, avec support rigide et fixation en tête. C''est le premier point de fuite d''une terrasse : une eau qui stagne au pied d''un relevé trop bas passe par-dessus."},{"titre":"Évacuations et trop-pleins","detail":"Entrées d''eau dimensionnées, avec platine adaptée au revêtement, plus un trop-plein en sécurité. Une évacuation obstruée sur une terrasse bois met la structure en charge d''eau : risque d''effondrement, pas seulement d''infiltration."},{"titre":"Ventilation de la lame d''air","detail":"Selon la configuration retenue, une lame d''air ventilée peut être exigée sous le support. Elle doit être réellement traversante, entrée et sortie dégagées, jamais obstruée par l''isolant."},{"titre":"Compatibilité des matériaux","detail":"Support, pare-vapeur, isolant, revêtement et fixations forment un système. On ne remplace pas un composant par un autre au prétexte qu''il est équivalent : c''est le système complet qui fait l''objet d''un avis technique."}]'::jsonb,
  common_errors = '[{"titre":"Absence de pare-vapeur","detail":"Le désordre le plus grave et le plus lent : condensation interne, pourrissement du platelage, découvert souvent trop tard, lors d''un affaissement."},{"titre":"Relevés trop courts","detail":"Typique en jonction avec une porte-fenêtre de plain-pied. L''eau passe au-dessus du relevé dès qu''elle stagne un peu. Correction difficile sans reprendre le seuil."},{"titre":"Étanchéité percée par la fixation d''un garde-corps","detail":"Platine vissée à travers le revêtement après coup. Chaque vis est une entrée d''eau directe dans la structure bois."},{"titre":"Évacuations non entretenues","detail":"Feuilles et mousses obstruent la crapaudine. La terrasse se transforme en bassin : surcharge, flèche, puis débordement par les relevés."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-43-4'),
  updated_at = now()
where lower(code) = lower('NF DTU 43.4');

update public.dtu_sheets set
  summary = 'Revêtements de sol scellés, posés sur mortier frais. Technique traditionnelle, encore la règle en extérieur et sur les grands formats en locaux à fort trafic.',
  key_points = '[{"titre":"Mortier de scellement et désolidarisation","detail":"Le revêtement scellé est posé sur une forme de mortier, elle-même désolidarisée du support par une interposition adaptée quand le support peut bouger. C''est cette désolidarisation qui absorbe les différences de mouvement entre support et carrelage."},{"titre":"Joints de fractionnement et périphériques","detail":"Fractionnement en panneaux de surface limitée, joints périphériques contre tous les murs et éléments traversants. Sans eux, la dilatation du carrelage pousse et provoque décollement en cloque, parfois avec bruit sec."},{"titre":"Pente et évacuation en extérieur","detail":"En terrasse ou balcon, pente régulière vers l''extérieur, sans contre-pente ni flache. L''eau qui stagne sur un carrelage extérieur finit par pénétrer les joints et geler dessous."},{"titre":"Choix du carreau selon l''usage","detail":"Résistance à l''abrasion, glissance, gélivité pour l''extérieur, format compatible avec la technique de pose. Un carreau non gélif posé en extérieur éclate au premier hiver."},{"titre":"Remplissage des joints et planéité","detail":"Joints remplis sur toute la profondeur, sans vide sous le carreau. Un carreau posé sur un lit incomplet sonne creux et casse au premier choc ponctuel."}]'::jsonb,
  common_errors = '[{"titre":"Joints de fractionnement supprimés pour l''esthétique","detail":"Décollement en cloque au centre des grandes surfaces, souvent l''été. Le carrelage se soulève d''un bloc : il n''y a pas de réparation locale."},{"titre":"Carrelage extérieur sans pente","detail":"Stagnation, infiltration dans les joints, gel et éclatement. Le désordre apparaît au deuxième ou troisième hiver."},{"titre":"Pose au plot sans respect du support","detail":"Mortier déposé en tas sous les angles seulement : vides sous le carreau, casse sous charge ponctuelle et son creux au sondage. Le sondage systématique au maillet est le bon réflexe d''expertise."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-52-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 52.1');

update public.dtu_sheets set
  summary = 'Travaux de peinture des bâtiments. C''est le lot le plus contesté en réception : la définition de l''état de finition attendu évite l''essentiel des litiges.',
  key_points = '[{"titre":"Trois états de finition","detail":"Finition élémentaire, courante ou soignée : ce sont trois niveaux d''exigence différents sur l''aspect, la planéité et la tolérance aux défauts. Le niveau doit être écrit au marché. Sans mention, c''est la finition courante qui s''applique, et le client attendait souvent la soignée."},{"titre":"Reconnaissance et préparation du support","detail":"Le support doit être sain, sec, propre, cohésif et compatible avec le système de peinture. Égrenage, rebouchage, enduit, ponçage, dépoussiérage : la préparation fait la qualité du résultat bien plus que la peinture elle-même."},{"titre":"Humidité du support","detail":"On ne peint pas un support humide. Sur maçonnerie ou enduit neuf, un délai de séchage est nécessaire avant mise en peinture, mesure à l''appui en cas de doute. Peindre trop tôt emprisonne l''eau : cloques et décollement."},{"titre":"Impression adaptée","detail":"Couche d''accrochage choisie selon le support : fixateur sur support poreux ou farinant, primaire anticorrosion sur métal, isolant sur taches. Sauter l''impression, c''est reporter le problème d''un an."},{"titre":"Conditions d''application","detail":"Températures et hygrométrie dans les plages admissibles, ni gel, ni forte chaleur, ni support ensoleillé en extérieur. Hors plage, le film ne se forme pas correctement : tendu irrégulier, adhérence médiocre."},{"titre":"Nombre de couches","detail":"Le système complet comporte impression et couches de finition ; l''opacité seule ne fait pas la conformité. Une couche unique sur un support neuf ne tient pas et ne donne pas l''aspect attendu."}]'::jsonb,
  common_errors = '[{"titre":"État de finition non défini au marché","detail":"Source numéro un des litiges de réception : le client voit des défauts que l''entreprise juge admissibles. Le niveau doit être écrit et, idéalement, montré sur une surface témoin."},{"titre":"Peinture sur support insuffisamment sec","detail":"Cloques et décollement par plaques, surtout sur enduit ciment récent ou après dégât des eaux mal séché."},{"titre":"Impression omise sur support poreux","detail":"Absorption irrégulière : le tendu est marbré, l''adhérence faible. Visible en lumière rasante, ce qui déclenche le litige."},{"titre":"Application hors conditions climatiques","detail":"Peinture appliquée trop froid ou en plein soleil : le film ne se forme pas, l''aspect devient mat par plaques et la durabilité s''effondre."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-59-1'),
  updated_at = now()
where lower(code) = lower('NF DTU 59.1');

update public.dtu_sheets set
  summary = 'Planchers chauffants à eau chaude. Un ouvrage noyé et donc irréparable : tout se joue avant le coulage de la chape.',
  key_points = '[{"titre":"Isolation sous les tubes","detail":"Isolant de résistance thermique adaptée, avec résistance à la compression suffisante pour supporter la chape et les charges. Sans isolant correct, une bonne part de la chaleur part vers le bas et les consommations explosent."},{"titre":"Bande périphérique et joints de dilatation","detail":"Bande compressible sur tout le pourtour, remontée jusqu''au niveau fini, et joints de dilatation découpant les grandes surfaces et les pièces de forme complexe. La chape chauffée se dilate beaucoup plus qu''une chape ordinaire."},{"titre":"Une seule boucle par pièce, sans raccord noyé","detail":"Chaque boucle est continue du collecteur au collecteur. Aucun raccord dans la dalle : un raccord noyé qui fuit impose de casser le sol pour le retrouver."},{"titre":"Essai de pression avant coulage","detail":"Mise en pression du réseau, maintenue pendant le coulage de la chape, avec constat écrit. C''est la seule occasion de détecter une perforation avant qu''elle ne soit inaccessible."},{"titre":"Enrobage des tubes par la chape","detail":"Hauteur de chape suffisante au-dessus des tubes pour diffuser la chaleur et résister aux charges. Trop peu de couverture donne un effet de zébrure thermique au sol et fissure au droit des tubes."},{"titre":"Limitation de la température de surface","detail":"La température au sol est plafonnée pour le confort et pour la santé : de l''ordre de 28 °C en zone de vie, un peu plus en zone périphérique. Le régulateur doit l''imposer, pas l''utilisateur."},{"titre":"Mise en chauffe progressive","detail":"Première mise en chauffe après séchage complet de la chape, par paliers, avant la pose du revêtement. Elle stabilise la chape et révèle les fissures avant qu''on ne colle le carrelage dessus."}]'::jsonb,
  common_errors = '[{"titre":"Essai de pression non réalisé ou non maintenu","detail":"Tube percé par une pointe ou un coup de truelle pendant le coulage, découvert à la mise en eau. Il faut alors localiser la fuite au thermographe et casser la chape."},{"titre":"Mise en chauffe trop rapide","detail":"Chape montée en température trop vite ou trop tôt : fissuration en grand, qui remonte ensuite dans le carrelage."},{"titre":"Revêtement incompatible","detail":"Parquet ou sol souple non prévu pour plancher chauffant, ou colle inadaptée : décollement, tuilage, jeux dans les lames. La compatibilité doit être écrite sur la documentation du produit."},{"titre":"Joints de dilatation absents","detail":"Sur grande surface ou pièce en L, la chape chauffée fissure systématiquement à l''angle rentrant. Le joint doit être prévu au bon endroit, et remonté dans le revêtement."}]'::jsonb,
  link = coalesce(link, 'https://www.boutique.afnor.org/fr-fr/recherche/dtu-65-14'),
  updated_at = now()
where lower(code) = lower('NF DTU 65.14');

-- ---------- Contrôle ----------
select count(*) filter (where key_points <> '[]'::jsonb) as documentees,
       count(*) filter (where key_points =  '[]'::jsonb) as encore_vides,
       count(*) as total
from public.dtu_sheets;
